
# Defines functions and macros useful for building project

MACRO(CLEAR_VARS)
	SET(LOCAL_C_FLAGS "")
	SET(LOCAL_CXX_FLAGS "")
	SET(LOCAL_SHARED_LINKER_FLAGS "")
	SET(LOCAL_MODULE_LINKER_FLAGS "")
	SET(LOCAL_EXE_LINKER_FLAGS "")
	SET(LOCAL_ASM_FLAGS "")

	SET(LOCAL_C_FILES "")
	SET(LOCAL_CXX_FILES "")
	SET(LOCAL_ASM_FILES "")
	SET(LOCAL_PATH "")
	SET(LOCAL_MODULE "")
	SET(LOCAL_LIBRARIES "")
ENDMACRO()

MACRO(PRINT_VARS)
	MESSAGE("")
	MESSAGE("LOCAL_COMMON_FLAGS        : ${LOCAL_COMMON_FLAGS}")
	MESSAGE("LOCAL_C_FLAGS             : ${LOCAL_C_FLAGS}")
	MESSAGE("LOCAL_CXX_FLAGS           : ${LOCAL_CXX_FLAGS}")
	MESSAGE("LOCAL_SHARED_LINKER_FLAGS : ${LOCAL_SHARED_LINKER_FLAGS}")
	MESSAGE("LOCAL_MODULE_LINKER_FLAGS : ${LOCAL_MODULE_LINKER_FLAGS}")
	MESSAGE("LOCAL_EXE_LINKER_FLAGS    : ${LOCAL_EXE_LINKER_FLAGS}")
	MESSAGE("LOCAL_ASM_FLAGS           : ${LOCAL_ASM_FLAGS}")
	
	MESSAGE("LOCAL_C_FILES             : ${LOCAL_C_FILES}")
	MESSAGE("LOCAL_CXX_FILES           : ${LOCAL_CXX_FILES}")
	MESSAGE("LOCAL_ASM_FILES           : ${LOCAL_ASM_FILES}")
	MESSAGE("LOCAL_PATH                : ${LOCAL_PATH}")
	MESSAGE("LOCAL_MODULE              : ${LOCAL_MODULE}")
	MESSAGE("LOCAL_LIBRARIES           : ${LOCAL_LIBRARIES}")
ENDMACRO()

MACRO(SET_FILES_FLAGS)
	IF(LOCAL_C_FILES AND LOCAL_C_FLAGS)
		SET_SOURCE_FILES_PROPERTIES(
			${LOCAL_C_FILES}
			PROPERTIES
			COMPILE_FLAGS "${LOCAL_C_FLAGS}"
		)
	ENDIF()

	IF(LOCAL_CXX_FILES AND LOCAL_CXX_FLAGS)
		SET_SOURCE_FILES_PROPERTIES(
			${LOCAL_CXX_FILES}
			PROPERTIES
			COMPILE_FLAGS "${LOCAL_CXX_FLAGS}"
		)
	ENDIF()

	IF(LOCAL_ASM_FILES AND LOCAL_ASM_FLAGS)
		SET_SOURCE_FILES_PROPERTIES(
			${LOCAL_ASM_FILES}
			PROPERTIES
			COMPILE_FLAGS "${LOCAL_ASM_FLAGS}"
		)
	ENDIF()
ENDMACRO()

MACRO(SET_MAKE_FLAGS)
	IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
	    SET(LOCAL_C_FLAGS   "${LOCAL_C_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_C_FLAGS} ${NGP_C_FLAGS_DEBUG}")
	    SET(LOCAL_CXX_FLAGS "${LOCAL_CXX_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_CXX_FLAGS} ${NGP_CXX_FLAGS_DEBUG}")
	    SET(LOCAL_ASM_FLAGS "${LOCAL_ASM_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_ASM_FLAGS}")
	ENDIF()

	IF(CMAKE_BUILD_TYPE STREQUAL "Release")
		SET(LOCAL_C_FLAGS   "${LOCAL_C_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_C_FLAGS} ${NGP_C_FLAGS_RELEASE}")
	    SET(LOCAL_CXX_FLAGS "${LOCAL_CXX_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_CXX_FLAGS} ${NGP_CXX_FLAGS_RELEASE}")
	    SET(LOCAL_ASM_FLAGS "${LOCAL_ASM_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_ASM_FLAGS}")
	ENDIF()

	IF(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
		SET(LOCAL_C_FLAGS   "${LOCAL_C_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_C_FLAGS} ${NGP_C_FLAGS_RELWITHDEBINFO}")
	    SET(LOCAL_CXX_FLAGS "${LOCAL_CXX_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_CXX_FLAGS} ${NGP_CXX_FLAGS_RELWITHDEBINFO}")
	    SET(LOCAL_ASM_FLAGS "${LOCAL_ASM_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_ASM_FLAGS}")
	ENDIF()

	IF(NGP_SHARED_LINKER_FLAGS)
		SET(LOCAL_SHARED_LINKER_FLAGS "${LOCAL_SHARED_LINKER_FLAGS} ${NGP_SHARED_LINKER_FLAGS}")
	ENDIF()

	IF(NGP_MODULE_LINKER_FLAGS)
		SET(LOCAL_MODULE_LINKER_FLAGS "${LOCAL_MODULE_LINKER_FLAGS} ${NGP_MODULE_LINKER_FLAGS}")
	ENDIF()

	IF(NGP_EXE_LINKER_FLAGS)
		SET(LOCAL_EXE_LINKER_FLAGS    "${LOCAL_EXE_LINKER_FLAGS} ${NGP_EXE_LINKER_FLAGS}")
	ENDIF()

	STRING(STRIP "${LOCAL_C_FLAGS}" LOCAL_C_FLAGS)
	STRING(STRIP "${LOCAL_CXX_FLAGS}" LOCAL_CXX_FLAGS)
	STRING(STRIP "${LOCAL_ASM_FLAGS}" LOCAL_ASM_FLAGS)
	STRING(STRIP "${LOCAL_SHARED_LINKER_FLAGS}" LOCAL_SHARED_LINKER_FLAGS)
	STRING(STRIP "${LOCAL_MODULE_LINKER_FLAGS}" LOCAL_MODULE_LINKER_FLAGS)
	STRING(STRIP "${LOCAL_EXE_LINKER_FLAGS}" LOCAL_EXE_LINKER_FLAGS)

	SET_FILES_FLAGS()
ENDMACRO()

MACRO(BUILD_EXECUTABLE)
	SET_MAKE_FLAGS()

	ADD_EXECUTABLE(${LOCAL_MODULE} ${LOCAL_C_FILES} ${LOCAL_CXX_FILES} ${LOCAL_ASM_FILES})

	IF(LOCAL_EXE_LINKER_FLAGS)
		TARGET_COMPILE_OPTIONs(${LOCAL_MODULE} PRIVATE ${LOCAL_EXE_LINKER_FLAGS})
	ENDIF()

	IF(LOCAL_LIBRARIES)
		FOREACH(LIB "${LOCAL_LIBRARIES}")
			TARGET_LINK_LIBRARIES(${LOCAL_MODULE} ${LIB}) 
		ENDFOREACH() 
	ENDIF()
ENDMACRO()

MACRO(BUILD_STATIC_LIBRARY)
	SET_MAKE_FLAGS()

	ADD_LIBRARY(${LOCAL_MODULE} STATIC ${LOCAL_C_FILES} ${LOCAL_CXX_FILES} ${LOCAL_ASM_FILES})

	IF(LOCAL_MODULE_LINKER_FLAGS)
		TARGET_COMPILE_OPTIONs(${LOCAL_MODULE} PRIVATE ${LOCAL_MODULE_LINKER_FLAGS})
	ENDIF()

	IF(LOCAL_LIBRARIES)
		FOREACH(LIB "${LOCAL_LIBRARIES}")
			TARGET_LINK_LIBRARIES(${LOCAL_MODULE} ${LIB}) 
		ENDFOREACH() 
	ENDIF()
ENDMACRO()

MACRO(BUILD_SHARED_LIBRARY)
	SET_MAKE_FLAGS()

	ADD_LIBRARY(${LOCAL_MODULE} SHARED ${LOCAL_C_FILES} ${LOCAL_CXX_FILES} ${LOCAL_ASM_FILES})

	IF(LOCAL_SHARED_LINKER_FLAGS)
		TARGET_COMPILE_OPTIONs(${LOCAL_MODULE} PRIVATE ${LOCAL_SHARED_LINKER_FLAGS})
	ENDIF()

	IF(LOCAL_LIBRARIES)
		FOREACH(LIB "${LOCAL_LIBRARIES}")
			TARGET_LINK_LIBRARIES(${LOCAL_MODULE} ${LIB}) 
		ENDFOREACH() 
	ENDIF()
ENDMACRO()

MACRO(BUILD_UNITTEST)
    SET(LOCAL_C_FLAGS          "${LOCAL_C_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_C_UNITTEST_FLAGS} ${NGP_C_FLAGS_DEBUG}")
    SET(LOCAL_CXX_FLAGS        "${LOCAL_CXX_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_CXX_UNITTEST_FLAGS} ${NGP_CXX_FLAGS_DEBUG}")
    SET(LOCAL_ASM_FLAGS        "${LOCAL_ASM_FLAGS} ${NGP_COMMON_FLAGS} ${NGP_ASM_FLAGS}")
    SET(LOCAL_EXE_LINKER_FLAGS "${LOCAL_EXE_LINKER_FLAGS} ${NGP_UNITTEST_LINKER_FLAGS}")

    STRING(STRIP "${LOCAL_C_FLAGS}" LOCAL_C_FLAGS)
	STRING(STRIP "${LOCAL_CXX_FLAGS}" LOCAL_CXX_FLAGS)
	STRING(STRIP "${LOCAL_ASM_FLAGS}" LOCAL_ASM_FLAGS)
	STRING(STRIP "${LOCAL_SHARED_LINKER_FLAGS}" LOCAL_SHARED_LINKER_FLAGS)
	STRING(STRIP "${LOCAL_MODULE_LINKER_FLAGS}" LOCAL_MODULE_LINKER_FLAGS)
	STRING(STRIP "${LOCAL_EXE_LINKER_FLAGS}" LOCAL_EXE_LINKER_FLAGS)

	SET_FILES_FLAGS()

	ADD_EXECUTABLE(${LOCAL_MODULE} ${LOCAL_C_FILES} ${LOCAL_CXX_FILES} ${LOCAL_ASM_FILES})

	IF(LOCAL_EXE_LINKER_FLAGS)
		TARGET_COMPILE_OPTIONs(${LOCAL_MODULE} PRIVATE ${LOCAL_EXE_LINKER_FLAGS})
	ENDIF()

	IF(LOCAL_LIBRARIES)
		FOREACH(LIB "${LOCAL_LIBRARIES}")
			TARGET_LINK_LIBRARIES(${LOCAL_MODULE} ${LIB}) 
		ENDFOREACH() 
	ENDIF()
	ADD_TEST(${LOCAL_MODULE} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${LOCAL_MODULE})
	SETUP_TARGET_FOR_COVERAGE("${LOCAL_MODULE}" "" "${PROJECT_BINARY_DIR}/lcov_report/${name}")
ENDMACRO()

